version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/golstyle-frontend
hooks:
  ApplicationStop:
    - location: scripts/stop_front.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/start_front.sh
      timeout: 300
      runas: root
